#!/usr/bin/env python3
"""Byte-for-byte baseline gate for the four pristine split targets.

Goldens are recorded from git object 84b50967, not regenerated by --check.
No output normalization is applied. The hook clock is frozen in the child
process so its bypass ledger is deterministic on every host.
"""

import argparse
import base64
import fcntl
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys


BASE = "84b50967d6f0cdf62b58b23b78cece5c0897c77e"
ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
CORPUS = ROOT / "scripts/tests/fixtures/pristine-harness/corpus.json"
GOLDENS = ROOT / "scripts/tests/fixtures/pristine-harness/goldens.json"
FILES = (
    "skills/golem-powers/_shared/shell_parse.py",
    "skills/golem-powers/_shared/harness_paths.py",
    "skills/golem-powers/tmp-block/hooks/tmp-block-pretooluse.py",
    "skills/golem-powers/git-guardian/git_safety.py",
    "skills/golem-powers/git-guardian/hooks/pre_tool_use.py",
    "scripts/repogolem/golem-dispatch.zsh",
    "scripts/repogolem/worktree-bootstrap.sh",
)
MUTATIONS = {
    "parser": (FILES[0], 'return _mask_data_argument_quotes("".join(output))',
               'return _mask_data_argument_quotes("x".join(output))'),
    "tmp-block": (FILES[2], '    sys.exit(0)\n\n\ndef advise',
                  '    sys.exit(1)\n\n\ndef advise'),
    "git-guardian": (FILES[3], 'Dangerous command: git push --force',
                     'Dangerous command: git push --forcE'),
    "launcher": (FILES[5], 'Unknown CLI:', 'Unknown CLi:'),
}
PARSER_PROBE = r'''
import importlib.util, json, sys
from pathlib import Path
p = Path(sys.argv[1]) / 'skills/golem-powers/_shared/shell_parse.py'
s = importlib.util.spec_from_file_location('shell_parse', p)
m = importlib.util.module_from_spec(s)
sys.modules[s.name] = m
s.loader.exec_module(m)
source = sys.stdin.read()
names = ('_shell_tokens', '_parse_bash', '_executable_subcommands',
         '_invoked_alias_bodies', 'shell_text_without_heredoc_bodies',
         'dollar_paren_bodies', 'without_dollar_paren_bodies')
out = {}
for name in names:
    try:
        out[name] = getattr(m, name)(source)
    except Exception as exc:
        out[name] = {'exception': type(exc).__name__, 'message': str(exc)}
print(json.dumps(out, sort_keys=True, ensure_ascii=False, default=repr))
'''
LAUNCHER_PROBE = r'''
source "$1" || exit $?
shift
function head() {
  if [[ "$1" == -c && "$2" == 16 && "$3" == /dev/urandom ]]; then
    print -rn -- '0123456789abcdef'
  else
    command head "$@"
  fi
}
function pristine_launch_env() {
  print -r -- "LAUNCH_CWD=$PWD"
  print -r -- "MCP_CONNECTION_NONBLOCKING=${MCP_CONNECTION_NONBLOCKING-}"
  print -r -- "CLAUDE_CODE_NO_FLICKER=${CLAUDE_CODE_NO_FLICKER-}"
}
function codex() {
  pristine_launch_env
  print -r -- "CODEX_ARGC=$#"
  local arg
  for arg in "$@"; do print -r -- "CODEX_ARG=$arg"; done
  local profile
  for profile in "$CODEX_HOME"/repogolem-*.config.toml(N); do
    cp "$profile" "$CAPTURE_PROFILE"
    print -r -- "PROFILE_MODE=$(stat -f %Lp "$profile" 2>/dev/null || stat -c %a "$profile")"
  done
}
function claude() {
  pristine_launch_env
  print -r -- "CLAUDE_ARGC=$#"
  for arg in "$@"; do print -r -- "CLAUDE_ARG=$arg"; done
}
function cursor() {
  pristine_launch_env
  print -r -- "CURSOR_ARGC=$#"
  for arg in "$@"; do print -r -- "CURSOR_ARG=$arg"; done
}
function agy() {
  pristine_launch_env
  print -r -- "AGY_ARGC=$#"
  for arg in "$@"; do print -r -- "AGY_ARG=$arg"; done
}
function bun() { print -r -- "BUN_ARGS=$*"; }
function npm() { print -r -- "NPM_ARGS=$*"; }
if [[ "$PRISTINE_PROFILE" == 1 ]]; then
  function _ralph_build_mcp_config() {
    print -r -- '{"mcpServers":{"fixture":{"command":"echo","args":["ready"]}}}'
  }
fi
_golem_dispatch "$@"
'''


def git_blob(path):
    return subprocess.run(
        ["git", "show", f"{BASE}:{path}"], cwd=ROOT, check=True,
        capture_output=True,
    ).stdout


def make_base(directory):
    for relative in FILES:
        target = directory / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(git_blob(relative))
        if relative.endswith("worktree-bootstrap.sh"):
            target.chmod(0o755)


def b64(data):
    return base64.b64encode(data).decode("ascii")


def fingerprint(result):
    """Keep machine-specific launcher fixture paths out of committed goldens."""
    return {"exit": result["exit"],
            "stdout_sha256": hashlib.sha256(base64.b64decode(result["stdout"])).hexdigest(),
            "stderr_sha256": hashlib.sha256(base64.b64decode(result["stderr"])).hexdigest(),
            "files_sha256": {name: hashlib.sha256(base64.b64decode(value)).hexdigest()
                             for name, value in result["files"].items()}}


def capture(case, tree, scratch):
    target = case["target"]
    ledger = scratch / "ledger.jsonl"
    if ledger.exists():
        ledger.unlink()
    env = {name: os.environ[name] for name in ("PATH", "LANG", "LC_ALL", "LC_CTYPE")
           if name in os.environ}
    env.update({"HOME": "/nonexistent", "TMPDIR": "/tmp/pristine-harness",
                "TZ": "UTC", "PYTHONHASHSEED": "0", "PYTHONDONTWRITEBYTECODE": "1",
                "TMP_BLOCK_LEDGER": str(ledger),
                "PYTHONPATH": str(HERE / "pristine-harness-clock")})
    env.update(case.get("env", {}))
    if target == "launcher":
        fixture = scratch / "launcher-fixture"
        if fixture.exists():
            shutil.rmtree(fixture)
        (fixture / "home/codex").mkdir(parents=True)
        (fixture / "project").mkdir()
        (fixture / "worktree").mkdir()
        (fixture / "runtime").mkdir()
        registry = fixture / "registry.json"
        registry.write_text(json.dumps({"projects": {"testrepo": {
            "path": str(fixture / "project"), "mcps": [], "clis": ["codex", "claude"]}}}))
        profile = fixture / "profile.toml"
        if case.get("package"):
            (fixture / "project/package.json").write_text('{"scripts":{"dev":"echo ready"},"packageManager":"bun@1"}\n')
        if case.get("sessions"):
            sessions = ROOT / "scripts/tests/fixtures/codex-sessions"
            for source in sessions.rglob("rollout-*.jsonl"):
                destination = fixture / "home/codex/sessions" / source.relative_to(sessions)
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_text(source.read_text().replace(
                    "__MATCHING_CWD__", str(fixture / "project")
                ).replace("__OTHER_CWD__", str(fixture / "other-project")))
                hour = int(source.name.split("T", 1)[1][:2])
                os.utime(destination, (1786496400 + hour * 3600,) * 2)
        launch_args = [arg.replace("{WORKTREE}", str(fixture / "worktree"))
                       for arg in case["args"]]
        env.update({"HOME": str(fixture / "home"),
                    "CODEX_HOME": str(fixture / "home/codex"),
                    "RALPH_REGISTRY_FILE": str(registry),
                    "CAPTURE_PROFILE": str(profile),
                    "XDG_RUNTIME_DIR": str(fixture / "runtime"),
                    "PRISTINE_PROFILE": "1" if case.get("profile") else "0"})
        argv = ["zsh", "-f", "-c", LAUNCHER_PROBE, "pristine-launcher",
                str(tree / "scripts/repogolem/golem-dispatch.zsh"), *launch_args]
        data = b""
    elif target == "parser":
        argv = [sys.executable, "-c", PARSER_PROBE, str(tree)]
        data = case["input"].encode()
    else:
        path = {
            "tmp-block": "skills/golem-powers/tmp-block/hooks/tmp-block-pretooluse.py",
            "git-guardian": "skills/golem-powers/git-guardian/hooks/pre_tool_use.py",
        }[target]
        argv = [sys.executable, str(tree / path)]
        data = case["input"].encode()
        if target == "git-guardian":
            env["GIT_GUARDIAN_LIB"] = str(tree / "skills/golem-powers/git-guardian")
    proc = subprocess.run(argv, input=data, capture_output=True, cwd="/",
                          env=env, timeout=15, check=False)
    files = {"ledger.jsonl": b64(ledger.read_bytes())} if ledger.exists() else {}
    if target == "launcher":
        files = {str(path.relative_to(fixture)): b64(path.read_bytes())
                 for path in fixture.rglob("*") if path.is_file()
                 and path != registry and path != fixture / "project/package.json"
                 and "sessions" not in path.relative_to(fixture).parts}
    return {"exit": proc.returncode, "stdout": b64(proc.stdout),
            "stderr": b64(proc.stderr), "files": files}


def execute(cases, tree, scratch):
    return {case["id"]: capture(case, tree, scratch) for case in cases}


def validate_baseline(cases, results):
    for kind in ("parser", "tmp-block", "git-guardian", "launcher"):
        rows = [results[case["id"]] for case in cases if case["target"] == kind]
        if not rows or all(row["exit"] != 0 for row in rows):
            raise RuntimeError(f"baseline fixture for {kind} did not run successfully")
    for case in cases:
        if case["target"] != "launcher":
            continue
        row = results[case["id"]]
        if case.get("profile") and (row["exit"] != 0 or "profile.toml" not in row["files"]):
            raise RuntimeError("launcher profile fixture did not publish a profile")
        if case.get("sessions") and (
            row["exit"] != 0 or b"CODEX_ARG=" not in base64.b64decode(row["stdout"])
        ):
            raise RuntimeError("Codex resume fixture did not reach the stub CLI")
        if case.get("package") and row["exit"] != 0:
            raise RuntimeError("run fixture did not reach the stub package launcher")
        if case["args"][1] == "gemini" and (
            row["exit"] != 0 or "project/.agents/mcp_config.json" not in row["files"]
        ):
            raise RuntimeError("Gemini fixture did not emit workspace config")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("record", "check", "verify-goldens", "mutation-proof"))
    parser.add_argument("--candidate-root", type=Path, default=ROOT)
    args = parser.parse_args()
    cases = json.loads(CORPUS.read_text())
    ids = [case["id"] for case in cases]
    if len(ids) != len(set(ids)) or any(case["target"] not in
       ("parser", "tmp-block", "git-guardian", "launcher") for case in cases):
        parser.error("duplicate case ID or unsupported target")
    # A stable fixture path keeps recorded launcher hashes reproducible here.
    # Lock it so concurrent invocations cannot compare each other's outputs.
    parent = ROOT / "docs.local/pristine-harness-runs"
    parent.mkdir(parents=True, exist_ok=True)
    with (parent / ".lock").open("w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        scratch = parent / "fixture"
        if scratch.exists():
            shutil.rmtree(scratch)
        scratch.mkdir()
        try:
            return run_locked(args, parser, cases, scratch)
        finally:
            shutil.rmtree(scratch)


def run_locked(args, parser, cases, scratch):
    base = scratch / "base"
    make_base(base)
    if args.action == "record":
        if GOLDENS.exists():
            parser.error("goldens already exist; do not overwrite the untouched base")
        result = execute(cases, base, scratch)
        validate_baseline(cases, result)
        committed = {case["id"]: fingerprint(result[case["id"]])
                     if case["target"] == "launcher" else result[case["id"]]
                     for case in cases}
        GOLDENS.write_text(json.dumps({"base": BASE, "results": committed},
                                     indent=2, sort_keys=True) + "\n")
        print(f"recorded {len(cases)} baseline cases from {BASE}")
        return 0
    if args.action == "mutation-proof":
        proof = {}
        for kind, (path, old, new) in MUTATIONS.items():
            mutated = scratch / kind
            shutil.copytree(base, mutated)
            source = mutated / path
            original = source.read_text()
            if original.count(old) != 1 or len(new) != len(old) + 1 and len(new) != len(old):
                parser.error(f"mutation anchor not unique or not one character: {kind}")
            subset = [case for case in cases if case["target"] == kind]
            baseline = execute(subset, mutated, scratch)
            source.write_text(original.replace(old, new))
            candidate = execute(subset, mutated, scratch)
            changed = [ident for ident in baseline if baseline[ident] != candidate[ident]]
            if not changed:
                parser.error(f"mutation escaped comparator: {kind}")
            proof[kind] = len(changed)
        print("MUTATION PROOF PASS " + json.dumps(proof, sort_keys=True))
        return 0
    expected = json.loads(GOLDENS.read_text())
    if expected["base"] != BASE or set(expected["results"]) != {case["id"] for case in cases}:
        parser.error("golden base SHA or case IDs do not match")
    measured = execute(cases, base, scratch)
    validate_baseline(cases, measured)
    committed = {case["id"]: fingerprint(measured[case["id"]])
                 if case["target"] == "launcher" else measured[case["id"]]
                 for case in cases}
    if args.action == "verify-goldens" and committed != expected["results"]:
        parser.error("recorded goldens differ from the immutable base on this host")
    actual = execute(cases, args.candidate_root.resolve(), scratch)
    failures = []
    for case in cases:
        ident = case["id"]
        baseline = measured[ident]
        if actual[ident] != baseline:
            differing = [key for key in ("exit", "stdout", "stderr", "files")
                         if actual[ident][key] != baseline[key]]
            failures.append(f"{ident}: {', '.join(differing)}")
    if failures:
        print("PRISTINE HARNESS FAIL\n" + "\n".join(failures), file=sys.stderr)
        return 1
    counts = {kind: sum(case["target"] == kind for case in cases)
              for kind in ("parser", "tmp-block", "git-guardian", "launcher")}
    print("PRISTINE HARNESS PASS " + json.dumps(counts, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
