#!/usr/bin/env python3
"""Byte-for-byte baseline gate for the four pristine split targets.

Goldens are recorded from git object 84b50967, not regenerated by --check.
No output normalization is applied. The hook clock is frozen in the child
process so its bypass ledger is deterministic on every host.
"""

import argparse
import base64
import fcntl
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import unicodedata


BASE = "84b50967d6f0cdf62b58b23b78cece5c0897c77e"
ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
CORPUS = ROOT / "scripts/tests/fixtures/pristine-harness/corpus.json"
GOLDENS = ROOT / "scripts/tests/fixtures/pristine-harness/goldens.json"
SEMANTIC_MUTANTS = ROOT / "scripts/tests/fixtures/pristine-harness/semantic-mutants.json"
DELTA_PATH = Path("scripts/tests/fixtures/pristine-harness/deltas.json")
# The fixture is disposable, but its spelling must not depend on a checkout.
# A shared lock serializes clones on one host; cleanup happens in main().
FIXTURE = Path("/var/tmp/pristine-harness-fixture")
FILES = (
    "skills/golem-powers/_shared/shell_parse.py",
    "skills/golem-powers/_shared/tests/test_shell_parse.py",
    "skills/golem-powers/_shared/harness_paths.py",
    "skills/golem-powers/tmp-block/hooks/tmp-block-pretooluse.py",
    "skills/golem-powers/git-guardian/git_safety.py",
    "skills/golem-powers/git-guardian/hooks/pre_tool_use.py",
    "scripts/repogolem/golem-dispatch.zsh",
    "scripts/repogolem/worktree-bootstrap.sh",
)
GIT_API_PROBE = r'''
import importlib.util, json, sys
from pathlib import Path
p = Path(sys.argv[1]) / 'skills/golem-powers/git-guardian/git_safety.py'
s = importlib.util.spec_from_file_location('git_safety', p)
m = importlib.util.module_from_spec(s)
sys.modules[s.name] = m
s.loader.exec_module(m)
request = json.load(sys.stdin)
try:
    result = getattr(m, request['function'])(*request.get('args', []),
                                               **request.get('kwargs', {}))
    print(json.dumps({'result': result}, sort_keys=True, ensure_ascii=False))
except Exception as exc:
    print(json.dumps({'exception': type(exc).__name__, 'message': str(exc)},
                     sort_keys=True, ensure_ascii=False))
'''
PARSER_PROBE = r'''
import importlib.util, json, sys
from pathlib import Path
p = Path(sys.argv[1]) / 'skills/golem-powers/_shared/shell_parse.py'
s = importlib.util.spec_from_file_location('shell_parse', p)
m = importlib.util.module_from_spec(s)
sys.modules[s.name] = m
s.loader.exec_module(m)
source = sys.stdin.read()
names = ('_shell_tokens', '_parse_bash', '_executable_subcommands',
         '_invoked_alias_bodies', 'shell_text_without_heredoc_bodies',
         'dollar_paren_bodies', 'without_dollar_paren_bodies')
out = {}
for name in names:
    try:
        out[name] = getattr(m, name)(source)
    except Exception as exc:
        out[name] = {'exception': type(exc).__name__, 'message': str(exc)}
print(json.dumps(out, sort_keys=True, ensure_ascii=False, default=repr))
'''
PARSER_DATA_PROBE = r'''
import importlib.util, json, sys
from pathlib import Path
p = Path(sys.argv[1]) / 'skills/golem-powers/_shared/shell_parse.py'
s = importlib.util.spec_from_file_location('shell_parse', p)
m = importlib.util.module_from_spec(s)
sys.modules[s.name] = m
s.loader.exec_module(m)
request = json.load(sys.stdin)
try:
    result = getattr(m, request['function'])(*request.get('args', []))
    print(json.dumps({'result': result}, sort_keys=True, ensure_ascii=False))
except Exception as exc:
    print(json.dumps({'exception': type(exc).__name__, 'message': str(exc)},
                     sort_keys=True, ensure_ascii=False))
'''
PARSER_HEREDOC_PROBE = r'''
import importlib.util, json, sys
from pathlib import Path
p = Path(sys.argv[1]) / 'skills/golem-powers/_shared/shell_parse.py'
s = importlib.util.spec_from_file_location('shell_parse', p)
m = importlib.util.module_from_spec(s)
sys.modules[s.name] = m
s.loader.exec_module(m)
source = sys.stdin.read()
print(json.dumps({
    'strip': m._strip_heredoc_bodies(source),
    'offset_mask': m._mask_heredoc_body_lines(source),
    'parse': m._parse_bash(source),
}, sort_keys=True, ensure_ascii=False, default=repr))
'''
PARSER_STATE_PROBE = r'''
import importlib.util, json, sys
from pathlib import Path
p = Path(sys.argv[1]) / 'skills/golem-powers/_shared/shell_parse.py'
s = importlib.util.spec_from_file_location('shell_parse', p)
m = importlib.util.module_from_spec(s)
sys.modules[s.name] = m
s.loader.exec_module(m)
request = json.load(sys.stdin)
state = request['state']
before = json.dumps(state, sort_keys=True)
invoked = m._invoked_alias_bodies(request['command'], state)
print(json.dumps({'invoked': invoked,
                  'state_unchanged': json.dumps(state, sort_keys=True) == before},
                 sort_keys=True, ensure_ascii=False))
'''
TMP_BLOCK_API_PROBE = r'''
import importlib.util, io, json, shutil, sys
from pathlib import Path
root = Path(sys.argv[1])
request = json.load(sys.stdin)
before = json.dumps(request, sort_keys=True)
def load(label, path):
    spec = importlib.util.spec_from_file_location(label, path)
    module = importlib.util.module_from_spec(spec)
    if request.get('registered', True):
        sys.modules[label] = module
    spec.loader.exec_module(module)
    return module
def main_capture(module, payload):
    old_in, old_out = sys.stdin, sys.stdout
    output = io.StringIO()
    try:
        sys.stdin, sys.stdout = io.StringIO(json.dumps(payload)), output
        try:
            module.main()
        except SystemExit as exc:
            code = exc.code
        else:
            raise RuntimeError('main returned without SystemExit')
    finally:
        sys.stdin, sys.stdout = old_in, old_out
    return {'exit': code, 'stdout': output.getvalue()}
if request.get('seam'):
    copies = Path(sys.argv[2])
    if copies.exists():
        shutil.rmtree(copies)
    modules = []
    for label in ('a', 'b'):
        powers = copies / label
        for leaf in ('tmp-block', '_shared'):
            shutil.copytree(root / 'skills/golem-powers' / leaf, powers / leaf,
                            ignore=shutil.ignore_patterns('__pycache__', '*.pyc', '.pytest_cache'))
        modules.append(load('tmp_api_' + label, powers / 'tmp-block/hooks/tmp-block-pretooluse.py'))
    a, b = modules
    if request['seam'] == 'classifier':
        a.in_temp_class = lambda raw: True
        b.in_temp_class = lambda raw: False
        path = '/durable/w7-probe'
    elif request['seam'] == 'prefixes':
        a._temp_prefixes = lambda: {'/w7-temp'}
        b._temp_prefixes = lambda: set()
        path = '/w7-temp/probe'
    else:
        raise ValueError('unsupported seam')
    payload = {'tool_name': 'Write', 'tool_input': {'file_path': path}, 'session_id': 'pristine'}
    result = [{'main': main_capture(m, payload),
               'prefix': m._literal_prefix_class(path + '$UNSET', None)} for m in (a, b)]
    budget = None
else:
    module = load('tmp_block_api_probe', root / 'skills/golem-powers/tmp-block/hooks/tmp-block-pretooluse.py')
    name = request['function']
    allowed = {'_bash_temp_targets', 'find_worktree_convention_issues', '_hatched_segments',
               '_bounded_brace_values', '_bounded_word_values', '_literal_array_values_before',
               '_bounded_compound_value_sets_before', '_static_shell_variable_state_before',
               'resolve_target', 'resolve_targets', '_literal_prefix_class'}
    if name not in allowed:
        raise ValueError('unsupported tmp-block API')
    args, kwargs = request.get('args', []), dict(request.get('kwargs', {}))
    command = request.get('command', '')
    budget = [request['budget']] if 'budget' in request else None
    if name in {'_bash_temp_targets', 'find_worktree_convention_issues', '_hatched_segments'}:
        args = ['Bash', {'command': command}] if name == 'find_worktree_convention_issues' else [command]
        if budget is not None:
            kwargs['_budget'] = budget
    elif request.get('parsed'):
        tokens, cmd, segs, scopes = module._parse_bash(command)
        index = max(i for i, token in enumerate(tokens) if token == request['raw'])
        variables = module._static_shell_variables_before(tokens, cmd, segs, segs[index])
        if name == '_static_shell_variable_state_before':
            args = [tokens, cmd, segs, segs[index]]
        elif name == '_literal_array_values_before':
            args = [tokens, cmd, index, variables, {}]
        elif name == '_bounded_compound_value_sets_before':
            args = [tokens, cmd, segs, scopes, index, variables]
        elif name == 'resolve_targets':
            args = [request['raw']]
            kwargs.update(tokens=tokens, cmd_pos=cmd, seg_of=segs, scope_of=scopes,
                          target_index=index, variables=variables)
        else:
            raise ValueError('unsupported parsed API')
    try:
        result = {'result': getattr(module, name)(*args, **kwargs)}
    except Exception as exc:
        result = {'exception': type(exc).__name__, 'message': str(exc)}
def encode(value):
    if isinstance(value, set):
        return sorted(value, key=repr)
    raise TypeError('unsupported API result type')
print(json.dumps({'call': result, 'budget': budget,
                  'request_unchanged': before == json.dumps(request, sort_keys=True)},
                 sort_keys=True, ensure_ascii=False, default=encode))
'''
IDENTITY_PROBE = r'''
import importlib.util, sys
from pathlib import Path
root = Path(sys.argv[1])
shared = root / 'skills/golem-powers/_shared'
sys.path.insert(0, str(shared))
def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module
shell_parse = load('shell_parse', shared / 'shell_parse.py')
hook = load('tmp_block_identity_probe', root / 'skills/golem-powers/tmp-block/hooks/tmp-block-pretooluse.py')
git_safety = load('git_safety', root / 'skills/golem-powers/git-guardian/git_safety.py')
tests = load('test_shell_parse_identity_probe', shared / 'tests/test_shell_parse.py')
hook_names = ''' + repr((
    '_ASSIGNMENT_RE', '_QUOTED_LBRACE', '_QUOTED_RBRACE',
    '_UNRESOLVED_EVAL_MARKER', '_WRAPPER_CMDS', '_WRAPPER_VALUE_OPTS',
    '_command_sub_word_continues', '_executable_subcommands',
    '_function_signature_parens', '_invoked_alias_bodies',
    '_is_command_sub_close', '_is_command_sub_open', '_is_separator',
    '_mask_function_definition_bodies', '_mask_quoted_operator_words',
    '_nested_alias_segment', '_nested_segment', '_parse_bash',
    '_segment_is_fully_exposed', '_segment_is_prefix',
    '_shell_command_payloads', '_shell_tokens', '_strip_heredoc_bodies',
)) + r'''
git_names = ('_backtick_bodies', 'dollar_paren_bodies',
             'shell_text_without_heredoc_bodies', 'without_dollar_paren_bodies')
test_names = ('_RAW_SHELL_TOKEN_RE', '_RAW_FOR_WORD_RE')
assert len(hook_names) == 23
for owner, names in ((hook, hook_names), (git_safety, git_names)):
    for name in names:
        assert getattr(owner, name) is getattr(shell_parse, name), name
assert tests.shell_parse is shell_parse
for name in test_names:
    assert getattr(tests.shell_parse, name) is getattr(shell_parse, name), name
# Each moved export must also be the very object held by its implementation
# module. This catches facade-side copies that importer-only checks miss.
impl_prefix = getattr(shell_parse, '_IMPL_NAME', '')
if impl_prefix:
    impl = {n: m for n, m in sys.modules.items()
            if n.startswith(impl_prefix + '.')}
    for name in set(hook_names) | set(test_names):
        owners = [m for m in impl.values() if name in vars(m)]
        defining = [m for m in owners
                    if getattr(getattr(m, name), '__module__', m.__name__) == m.__name__]
        for module in defining or owners:
            assert getattr(shell_parse, name) is getattr(module, name), ('facade!=impl', name, module.__name__)
print('IDENTITY PASS hook=23 git=4 test=2')
'''
LAUNCHER_PROBE = r'''
source "$1" || exit $?
shift
function head() {
  if [[ "$1" == -c && "$2" == 16 && "$3" == /dev/urandom ]]; then
    print -rn -- '0123456789abcdef'
  else
    command head "$@"
  fi
}
function pristine_launch_env() {
  print -r -- "LAUNCH_CWD=$PWD"
  print -r -- "MCP_CONNECTION_NONBLOCKING=${MCP_CONNECTION_NONBLOCKING-}"
  print -r -- "CLAUDE_CODE_NO_FLICKER=${CLAUDE_CODE_NO_FLICKER-}"
  local staged=("$XDG_RUNTIME_DIR"/repogolem/testrepo/repogolem-*-agent.*(N))
  print -r -- "PERSONA_STAGED=${#staged}"
  if (( ${#staged} )); then
    print -r -- "PERSONA_MODE=$(stat -c %a "$staged[1]" 2>/dev/null || stat -f %Lp "$staged[1]")"
  fi
}
function codex() {
  pristine_launch_env
  print -r -- "CODEX_ARGC=$#"
  local arg
  for arg in "$@"; do print -r -- "CODEX_ARG=$arg"; done
  local profile
  for profile in "$CODEX_HOME"/repogolem-*.config.toml(N); do
    cp "$profile" "$CAPTURE_PROFILE"
    print -r -- "PROFILE_MODE=$(stat -c %a "$profile" 2>/dev/null || stat -f %Lp "$profile")"
  done
}
function claude() {
  pristine_launch_env
  print -r -- "CLAUDE_ARGC=$#"
  for arg in "$@"; do print -r -- "CLAUDE_ARG=$arg"; done
}
function cursor() {
  pristine_launch_env
  print -r -- "CURSOR_ARGC=$#"
  for arg in "$@"; do print -r -- "CURSOR_ARG=$arg"; done
}
function agy() {
  pristine_launch_env
  print -r -- "AGY_ARGC=$#"
  for arg in "$@"; do print -r -- "AGY_ARG=$arg"; done
}
function bun() { print -r -- "BUN_ARGS=$*"; }
function npm() { print -r -- "NPM_ARGS=$*"; }
if [[ "$PRISTINE_PROFILE" == 1 || "$PRISTINE_MCP_MERGE" == 1 ]]; then
  function _ralph_build_mcp_config() {
    print -r -- '{"mcpServers":{"fixture":{"command":"echo","args":["ready"]}}}'
  }
fi
_golem_dispatch "$@"
'''


def git_blob(path):
    return subprocess.run(
        ["git", "show", f"{BASE}:{path}"], cwd=ROOT, check=True,
        capture_output=True,
    ).stdout


def make_base(directory):
    for relative in FILES:
        target = directory / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(git_blob(relative))
        if relative.endswith("worktree-bootstrap.sh"):
            target.chmod(0o755)


def copy_candidate_for_mutation(source, destination):
    """Copy the candidate before semantic mutation so interrupts cannot dirty it."""
    return shutil.copytree(
        source.resolve(),
        destination,
        ignore=shutil.ignore_patterns(
            ".git", ".worktrees", ".venv", "__pycache__", "node_modules",
            "coverage", "docs.local",
        ),
    )


def b64(data):
    return base64.b64encode(data).decode("ascii")


def fingerprint(result):
    """Keep machine-specific launcher fixture paths out of committed goldens."""
    return {"exit": result["exit"],
            "stdout_sha256": hashlib.sha256(base64.b64decode(result["stdout"])).hexdigest(),
            "stderr_sha256": hashlib.sha256(base64.b64decode(result["stderr"])).hexdigest(),
            "files_sha256": {name: hashlib.sha256(base64.b64decode(value)).hexdigest()
                             for name, value in result["files"].items()}}


def expected_on_host(goldens):
    """Choose recorded raw bytes for this host, never normalize hook output."""
    expected = goldens["results"].copy()
    expected.update(goldens.get("platform_results", {}).get(sys.platform, {}))
    return expected


def capture_digest(result):
    """Hash the complete capture, including exit, raw base64 bytes and files."""
    data = json.dumps(result, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(data).hexdigest()


def reject_duplicate_keys(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def normalize_metadata(value):
    if not isinstance(value, str):
        return ""
    return "".join(char for char in unicodedata.normalize("NFKC", value)
                   if unicodedata.category(char) != "Cf" and not char.isspace())


def visible_metadata(value):
    return bool(value) and any(char.isalnum() for char in value) and value.casefold() not in {
        "x", "tbd", "todo", "n/a", "none", "-",
    }


def ruling_reference(value):
    normalized = normalize_metadata(value)
    pattern = r"(golems#\d+|https://github\.com/[\w.-]+/[\w.-]+/(issues|pull)/\d+(#[\w-]+)?|collab:\d{4}-\d{2}-\d{2}:.{8,})"
    return normalized if visible_metadata(normalized) and re.fullmatch(pattern, normalized) else None


def delta_metadata(reason, authority):
    reason, authority = normalize_metadata(reason), normalize_metadata(authority)
    if not visible_metadata(reason) or not visible_metadata(authority):
        raise ValueError("delta reason and authority must be nonempty strings with visible alphanumeric content, not placeholders")
    if not ruling_reference(authority):
        raise ValueError("delta authority requires a concrete lead ruling reference")
    return reason, authority


def load_deltas(path, ids):
    rows = json.loads(path.read_text(), object_pairs_hook=reject_duplicate_keys) if path.exists() else []
    if not isinstance(rows, list):
        raise ValueError("deltas must be a list")
    seen = set()
    for row in rows:
        required = {"case", "reason", "authority", "candidate_sha256"}
        if not isinstance(row, dict) or not required <= set(row) or set(row) - required - {"allow_deny_to_allow"}:
            raise ValueError("delta requires case, reason, authority and candidate_sha256")
        if not isinstance(row["case"], str) or not row["case"].strip():
            raise ValueError("delta case must be a nonempty string")
        row["reason"], row["authority"] = delta_metadata(row["reason"], row["authority"])
        if "allow_deny_to_allow" in row:
            ruling = ruling_reference(row["allow_deny_to_allow"])
            if not ruling:
                raise ValueError("allow_deny_to_allow requires a concrete lead ruling reference")
            row["allow_deny_to_allow"] = ruling
        ident = row["case"]
        if ident in seen:
            raise ValueError(f"duplicate delta case: {ident}")
        if ident not in ids:
            raise ValueError(f"unknown delta case: {ident}")
        seen.add(ident)
        hashes = row["candidate_sha256"]
        if not isinstance(hashes, dict) or any(
            host not in ("darwin", "linux") or not isinstance(digest, str)
            or re.fullmatch(r"[0-9a-f]{64}", digest) is None
            for host, digest in hashes.items()
        ):
            raise ValueError(f"invalid platform hashes for delta: {ident}")
    return rows


def compare_captures(baseline, actual, declarations, platform, hook_cases=()):
    declared = {row["case"]: row for row in declarations}
    failures, used = [], 0
    for ident, base in baseline.items():
        candidate = actual[ident]
        row = declared.get(ident)
        if row is not None:
            observed = capture_digest(candidate)
            deny_to_allow = ident in hook_cases and base["exit"] == 2 and candidate["exit"] != 2
            if deny_to_allow:
                print("PRISTINE DELTA DENY→ALLOW " + json.dumps({
                    "case": ident, "base_exit": base["exit"], "candidate_exit": candidate["exit"],
                    "allow_deny_to_allow": row.get("allow_deny_to_allow"),
                }, sort_keys=True))
            if deny_to_allow and not ruling_reference(row.get("allow_deny_to_allow")):
                failures.append(f"{ident}: hook deny→allow requires allow_deny_to_allow lead ruling reference")
            elif candidate == base:
                failures.append(f"{ident}: stale delta (candidate equals immutable base); observed sha256={observed}")
            elif platform not in row["candidate_sha256"]:
                failures.append(f"{ident}: missing {platform} delta hash; observed sha256={observed}")
            elif observed != row["candidate_sha256"][platform]:
                failures.append(f"{ident}: delta hash mismatch; observed sha256={observed}")
            else:
                used += 1
                print("PRISTINE DELTA USED " + json.dumps({
                    key: row[key] for key in ("case", "reason", "authority")
                }, sort_keys=True))
        elif candidate != base:
            differing = [key for key in ("exit", "stdout", "stderr", "files") if candidate[key] != base[key]]
            failures.append(f"{ident}: undeclared difference ({', '.join(differing)})")
    return failures, used


def record_delta(path, ids, case, reason, authority, result, platform):
    rows = load_deltas(path, ids)
    reason, authority = delta_metadata(reason, authority)
    if case not in ids:
        raise ValueError("record-delta requires a known case, reason and authority")
    row = next((row for row in rows if row["case"] == case), None)
    if row is None:
        row = {"case": case, "reason": reason, "authority": authority, "candidate_sha256": {}}
        rows.append(row)
    row.update(reason=reason, authority=authority)
    row["candidate_sha256"][platform] = capture_digest(result)
    path.write_text(json.dumps(sorted(rows, key=lambda row: row["case"]), indent=2, sort_keys=True) + "\n")
    print(f"recorded delta {case} {platform} sha256={row['candidate_sha256'][platform]}")


def fixture_cwd(scratch, name):
    names = {
        "root": scratch / "repo",
        "subdir": scratch / "repo/docs.local/safe",
        "worktree": scratch / "repo/.worktrees/lane",
        "nested": scratch / "repo/docs.local/clone",
        "nested-worktree": scratch / "repo/docs.local/clone/.worktrees/lane",
    }
    if name not in names:
        raise ValueError(f"unsupported fixture cwd: {name}")
    return names[name]


def make_fixture(scratch):
    repo = scratch / "repo"
    (repo / ".git/worktrees/lane").mkdir(parents=True)
    (repo / "docs.local/safe").mkdir(parents=True)
    worktree = repo / ".worktrees/lane"
    worktree.mkdir(parents=True)
    (worktree / ".git").write_text(f"gitdir: {repo}/.git/worktrees/lane\n")
    nested = repo / "docs.local/clone"
    (nested / ".git/worktrees/lane").mkdir(parents=True)
    nested_worktree = nested / ".worktrees/lane"
    nested_worktree.mkdir(parents=True)
    (nested_worktree / ".git").write_text(
        f"gitdir: {nested}/.git/worktrees/lane\n")


def materialize(value, scratch):
    if isinstance(value, str):
        for token, path in (("{REPO}", scratch / "repo"),
                            ("{WORKTREE}", scratch / "repo/.worktrees/lane"),
                            ("{NESTED}", scratch / "repo/docs.local/clone"),
                            ("{SCRATCHPAD}", Path("/tmp/claude-501/pristine-harness/"
                                "01234567-89ab-cdef-0123-456789abcdef/scratchpad"))):
            value = value.replace(token, str(path))
        return value
    if isinstance(value, list):
        return [materialize(item, scratch) for item in value]
    if isinstance(value, dict):
        return {key: materialize(item, scratch) for key, item in value.items()}
    return value


def capture(case, tree, scratch):
    target = case["target"]
    ledger = scratch / "ledger.jsonl"
    if ledger.exists():
        ledger.unlink()
    env = {name: os.environ[name] for name in ("PATH", "LANG", "LC_ALL", "LC_CTYPE")
           if name in os.environ}
    env.update({"HOME": "/nonexistent", "TMPDIR": "/tmp/pristine-harness",
                "TZ": "UTC", "PYTHONHASHSEED": "0", "PYTHONDONTWRITEBYTECODE": "1",
                "TMP_BLOCK_LEDGER": str(ledger),
                "PYTHONPATH": str(HERE / "pristine-harness-clock")})
    env.update(materialize(case.get("env", {}), scratch))
    cwd = fixture_cwd(scratch, case["cwd"]) if case.get("cwd") else Path("/")
    if target == "launcher":
        fixture = scratch / "launcher-fixture"
        if fixture.exists():
            shutil.rmtree(fixture)
        (fixture / "home/codex").mkdir(parents=True)
        (fixture / "project").mkdir()
        (fixture / "worktree").mkdir()
        (fixture / "runtime").mkdir()
        registry = fixture / "registry.json"
        project = {"path": str(fixture / "project"), "mcps": [],
                   "clis": ["codex", "claude", "cursor", "gemini"]}
        if case.get("persona"):
            agent = fixture / "home/.claude/agents/test-agent.md"
            agent.parent.mkdir(parents=True)
            agent.write_text("---\nname: test-agent\ninitialPrompt: |\n"
                             "  Search BrainLayer first.\n---\n"
                             "# Full orchestrator protocol\nUse repository context.\n")
            project["agent"] = "test-agent"
            project["mcps"] = ["brainlayer"]
        registry_data = {"projects": {"testrepo": project}}
        if case.get("mcp_merge"):
            # AGY now reads static declarations, not the resolving builder stub.
            # The immutable dispatcher still sees exactly the same stub map.
            registry_data["global"] = {"mcps": {"fixture": {"command": "echo", "args": ["ready"]}}}
        registry.write_text(json.dumps(registry_data))
        profile = fixture / "profile.toml"
        if case.get("mcp_merge"):
            (fixture / "project/.mcp.json").write_text(
                '{"mcpServers":{"repo":{"command":"repo-mcp"}}}\n')
        if case.get("package"):
            (fixture / "project/package.json").write_text('{"scripts":{"dev":"echo ready"},"packageManager":"bun@1"}\n')
        if case.get("sessions"):
            sessions = ROOT / "scripts/tests/fixtures/codex-sessions"
            for source in sessions.rglob("rollout-*.jsonl"):
                destination = fixture / "home/codex/sessions" / source.relative_to(sessions)
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_text(source.read_text().replace(
                    "__MATCHING_CWD__", str(fixture / "project")
                ).replace("__OTHER_CWD__", str(fixture / "other-project")))
                hour = int(source.name.split("T", 1)[1][:2])
                os.utime(destination, (1786496400 + hour * 3600,) * 2)
        launch_args = [arg.replace("{WORKTREE}", str(fixture / "worktree"))
                       for arg in case["args"]]
        env.update({"HOME": str(fixture / "home"),
                    "CODEX_HOME": str(fixture / "home/codex"),
                    "RALPH_REGISTRY_FILE": str(registry),
                    "CAPTURE_PROFILE": str(profile),
                    "XDG_RUNTIME_DIR": str(fixture / "runtime"),
                    "PRISTINE_PROFILE": "1" if case.get("profile") else "0",
                    "PRISTINE_MCP_MERGE": "1" if case.get("mcp_merge") else "0"})
        argv = ["zsh", "-f", "-c", LAUNCHER_PROBE, "pristine-launcher",
                str(tree / "scripts/repogolem/golem-dispatch.zsh"), *launch_args]
        data = b""
    elif target in ("parser", "parser-state", "parser-identity"):
        probe = {"parser": (PARSER_HEREDOC_PROBE if case.get("probe") == "heredoc-models"
                            else PARSER_DATA_PROBE if case.get("probe") == "data-substitution"
                            else PARSER_PROBE), "parser-state": PARSER_STATE_PROBE,
                 "parser-identity": IDENTITY_PROBE}[target]
        argv = [sys.executable, "-c", probe, str(tree)]
        data = (json.dumps(case["request"]).encode()
                if target == "parser-state" or case.get("probe") == "data-substitution"
                else case.get("input", "").encode())
    elif target == "tmp-block-api":
        argv = [sys.executable, "-c", TMP_BLOCK_API_PROBE, str(tree), str(scratch / "api-copies")]
        data = json.dumps(materialize(case["request"], scratch)).encode()
    elif target == "git-api":
        argv = [sys.executable, "-c", GIT_API_PROBE, str(tree)]
        data = json.dumps(materialize(case["request"], scratch)).encode()
    else:
        path = {
            "tmp-block": "skills/golem-powers/tmp-block/hooks/tmp-block-pretooluse.py",
            "git-guardian": "skills/golem-powers/git-guardian/hooks/pre_tool_use.py",
        }[target]
        argv = [sys.executable, str(tree / path)]
        data = materialize(case["input"], scratch).encode()
        if target == "git-guardian":
            env["GIT_GUARDIAN_LIB"] = str(tree / "skills/golem-powers/git-guardian")
    proc = subprocess.run(argv, input=data, capture_output=True, cwd=cwd,
                          env=env, timeout=15, check=False)
    files = {"ledger.jsonl": b64(ledger.read_bytes())} if ledger.exists() else {}
    if target == "launcher":
        files = {str(path.relative_to(fixture)): b64(path.read_bytes())
                 for path in fixture.rglob("*") if path.is_file()
                 and path != registry and path != fixture / "project/package.json"
                 and path != fixture / "project/.mcp.json"
                 and "agents" not in path.relative_to(fixture).parts
                 and "sessions" not in path.relative_to(fixture).parts}
    return {"exit": proc.returncode, "stdout": b64(proc.stdout),
            "stderr": b64(proc.stderr), "files": files}


def execute(cases, tree, scratch):
    return {case["id"]: capture(case, tree, scratch) for case in cases}


def validate_baseline(cases, results):
    for kind in ("parser", "parser-state", "parser-identity", "tmp-block", "tmp-block-api",
                 "git-guardian", "git-api", "launcher"):
        rows = [results[case["id"]] for case in cases if case["target"] == kind]
        if not rows or all(row["exit"] != 0 for row in rows):
            raise RuntimeError(f"baseline fixture for {kind} did not run successfully")
    for case in cases:
        if "expected_invoked" not in case:
            continue
        row = results[case["id"]]
        if row["exit"] != 0:
            raise RuntimeError(f"explicit parser case failed: {case['id']}")
        output = json.loads(base64.b64decode(row["stdout"]))
        invoked = (output["_invoked_alias_bodies"] if case["target"] == "parser"
                   else output["invoked"])
        if invoked != case["expected_invoked"]:
            raise RuntimeError(f"explicit parser tuples differ: {case['id']}")
        if case["target"] == "parser-state" and not output["state_unchanged"]:
            raise RuntimeError(f"initial state mutated: {case['id']}")
    for case in cases:
        if case["target"] != "launcher":
            continue
        row = results[case["id"]]
        if case.get("profile") and (row["exit"] != 0 or "profile.toml" not in row["files"]):
            raise RuntimeError("launcher profile fixture did not publish a profile")
        if case.get("sessions") and (
            row["exit"] != 0 or b"CODEX_ARG=" not in base64.b64decode(row["stdout"])
        ):
            raise RuntimeError("Codex resume fixture did not reach the stub CLI")
        if case.get("package") and row["exit"] != 0:
            raise RuntimeError("run fixture did not reach the stub package launcher")
        if case["args"][1] == "gemini" and (
            row["exit"] != 0 or "project/.agents/mcp_config.json" not in row["files"]
        ):
            raise RuntimeError("Gemini fixture did not emit workspace config")
        if case.get("persona"):
            stdout = base64.b64decode(row["stdout"])
            worker = case.get("env", {}).get("GOLEM_ROLE") == "worker"
            if case["args"][1] == "claude":
                if b"CLAUDE_ARG=--agent\nCLAUDE_ARG=test-agent" not in stdout:
                    raise RuntimeError("Claude persona fixture did not pass the agent")
            elif worker:
                if b"PERSONA_STAGED=0" not in stdout or b"<agent_context>" in stdout:
                    raise RuntimeError("worker fixture inherited lead persona")
            elif (b"PERSONA_STAGED=1" not in stdout or
                  b"PERSONA_MODE=600" not in stdout or
                  b"BrainLayer-first ambiguity gate" not in stdout):
                raise RuntimeError("lead persona or ambiguity gate fixture did not execute")
        if case.get("mcp_merge"):
            config = row["files"].get("project/.agents/mcp_config.json")
            if not config or not {"fixture", "repo"}.issubset(
                json.loads(base64.b64decode(config)).get("mcpServers", {})
            ):
                raise RuntimeError("agy fixture did not merge both MCP sources")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("record", "record-delta", "check", "verify-goldens",
                                          "verify-python-goldens", "mutation-proof"))
    parser.add_argument("--candidate-root", type=Path, default=ROOT)
    for option in ("case", "reason", "authority"):
        parser.add_argument(f"--{option}")
    args = parser.parse_args()
    if args.action == "record-delta" and any(not getattr(args, key) for key in ("case", "reason", "authority")):
        parser.error("record-delta requires --case, --reason and --authority")
    cases = json.loads(CORPUS.read_text())
    ids = [case["id"] for case in cases]
    if len(ids) != len(set(ids)) or any(case["target"] not in
       ("parser", "parser-state", "parser-identity", "tmp-block", "tmp-block-api",
        "git-guardian", "git-api", "launcher") for case in cases):
        parser.error("duplicate case ID or unsupported target")
    # Lock concurrent invocations before touching the checkout-independent fixture.
    with Path("/var/tmp/pristine-harness-fixture.lock").open("w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        scratch = FIXTURE
        if scratch.exists():
            shutil.rmtree(scratch)
        scratch.mkdir()
        try:
            make_fixture(scratch)
            return run_locked(args, parser, cases, scratch)
        finally:
            shutil.rmtree(scratch)


def run_locked(args, parser, cases, scratch):
    base = scratch / "base"
    make_base(base)
    if args.action == "record-delta":
        selected = [case for case in cases if case["id"] == args.case]
        if not selected:
            parser.error(f"unknown delta case: {args.case}")
        baseline = execute(selected, base, scratch)
        actual = execute(selected, args.candidate_root.resolve(), scratch)
        if actual[args.case] == baseline[args.case]:
            parser.error(f"stale delta: {args.case} equals immutable base")
        try:
            record_delta(args.candidate_root / DELTA_PATH, [case["id"] for case in cases],
                         args.case, args.reason, args.authority, actual[args.case], sys.platform)
        except ValueError as error:
            parser.error(str(error))
        return 0
    if args.action == "record":
        if GOLDENS.exists():
            parser.error("goldens already exist; do not overwrite the untouched base")
        result = execute(cases, base, scratch)
        validate_baseline(cases, result)
        committed = {case["id"]: fingerprint(result[case["id"]])
                     if case["target"] == "launcher" else result[case["id"]]
                     for case in cases}
        GOLDENS.write_text(json.dumps({"base": BASE, "results": committed},
                                     indent=2, sort_keys=True) + "\n")
        print(f"recorded {len(cases)} baseline cases from {BASE}")
        return 0
    if args.action == "mutation-proof":
        mutants = json.loads(SEMANTIC_MUTANTS.read_text())
        if not mutants or len({row["id"] for row in mutants}) != len(mutants):
            parser.error("the reviewer semantic set must contain distinct mutants")
        baseline = {}
        caught = {}
        candidate_mutation_tree = None
        if any(row.get("baseline") == "candidate" for row in mutants):
            candidate_mutation_tree = copy_candidate_for_mutation(
                args.candidate_root, scratch / "candidate"
            )
        for row in mutants:
            kind = row["target"]
            subset = [case for case in cases if case["target"] == kind]
            mutation_tree = (candidate_mutation_tree
                             if row.get("baseline") == "candidate" else base)
            baseline_key = (kind, str(mutation_tree))
            if baseline_key not in baseline:
                baseline[baseline_key] = execute(subset, mutation_tree, scratch)
            source = mutation_tree / row["path"]
            original = source.read_text()
            operation = row.get("operation", "replace")
            if operation == "replace":
                if original.count(row["old"]) != 1 or row["new"] == row["old"]:
                    parser.error(f"mutation anchor is not unique or semantic: {row['id']}")
                mutated = original.replace(row["old"], row["new"])
            elif operation == "swap-passes":
                markers = (row["old"], row["middle"], row["end"])
                if any(original.count(marker) != 1 for marker in markers):
                    parser.error(f"mutation anchor is not unique: {row['id']}")
                start = original.index(row["old"]) + row["old"].index("        for i, token")
                middle = original.index(row["middle"])
                end = original.index(row["end"])
                if not start < middle < end:
                    parser.error(f"mutation pass order is invalid: {row['id']}")
                mutated = (original[:start] + original[middle:end] +
                           original[start:middle] + original[end:])
            elif operation == "move-before":
                markers = (row["old"], row["end"], row["before"])
                if any(original.count(marker) != 1 for marker in markers):
                    parser.error(f"mutation anchor is not unique: {row['id']}")
                start = original.index(row["old"])
                end = original.index(row["end"])
                before = original.index(row["before"])
                if not before < start < end:
                    parser.error(f"mutation move order is invalid: {row['id']}")
                mutated = (original[:before] + original[start:end] +
                           original[before:start] + original[end:])
            elif operation == "move-line-before":
                line, marker = row["old"], row["before"]
                if original.count(line) != 1 or original.count(marker) != 1:
                    parser.error(f"mutation anchor is not unique: {row['id']}")
                start, before = original.index(line), original.index(marker)
                if not before < start:
                    parser.error(f"mutation move order is invalid: {row['id']}")
                mutated = (original[:before] + line + original[before:start] +
                           original[start + len(line):])
            else:
                parser.error(f"unknown mutation operation: {row['id']}")
            try:
                source.write_text(mutated)
                candidate = execute(subset, mutation_tree, scratch)
            finally:
                source.write_text(original)
            changed = [ident for ident in baseline[baseline_key]
                       if baseline[baseline_key][ident] != candidate[ident]]
            if not changed:
                parser.error(f"semantic mutant escaped: {row['id']} {row['description']}")
            caught[row["id"]] = changed
            print(f"CAUGHT {row['id']} {len(changed)} {changed[:3]}", flush=True)
        print(f"SEMANTIC MUTATION PROOF PASS {len(caught)}/{len(mutants)}")
        return 0
    expected = json.loads(GOLDENS.read_text())
    if expected["base"] != BASE or set(expected["results"]) != {case["id"] for case in cases}:
        parser.error("golden base SHA or case IDs do not match")
    host_goldens = expected_on_host(expected)
    if args.action == "verify-python-goldens":
        python_cases = [case for case in cases if case["target"] != "launcher"]
        measured_python = execute(python_cases, base, scratch)
        stale = [case["id"] for case in python_cases
                 if measured_python[case["id"]] != host_goldens[case["id"]]]
        if stale:
            parser.error(f"recorded Python goldens differ from immutable base: {stale[:8]}")
        print(f"PYTHON GOLDENS PASS {len(python_cases)}")
        return 0
    measured = execute(cases, base, scratch)
    validate_baseline(cases, measured)
    committed = {case["id"]: fingerprint(measured[case["id"]])
                 if case["target"] == "launcher" else measured[case["id"]]
                 for case in cases}
    python_ids = {case["id"] for case in cases if case["target"] != "launcher"}
    stale_python = [ident for ident in python_ids
                    if committed[ident] != host_goldens[ident]]
    if stale_python:
        parser.error(f"recorded Python goldens differ from immutable base: {stale_python[:8]}")
    if args.action == "verify-goldens" and committed != host_goldens:
        stale = [ident for ident in committed if committed[ident] != host_goldens[ident]]
        parser.error(f"recorded launcher goldens differ from immutable base: {stale[:8]}")
    if args.action == "verify-goldens":
        print(f"GOLDENS PASS {len(cases)}")
        return 0
    actual = execute(cases, args.candidate_root.resolve(), scratch)
    try:
        deltas = load_deltas(args.candidate_root / DELTA_PATH, [case["id"] for case in cases])
    except ValueError as error:
        parser.error(str(error))
    failures, used = compare_captures(measured, actual, deltas, sys.platform,
                                      hook_cases={case["id"] for case in cases
                                                  if case["target"] in ("tmp-block", "git-guardian")})
    print(f"PRISTINE DECLARED DELTAS USED {used}")
    if failures:
        print("PRISTINE HARNESS FAIL\n" + "\n".join(failures), file=sys.stderr)
        return 1
    counts = {kind: sum(case["target"] == kind for case in cases)
              for kind in ("parser", "parser-state", "parser-identity",
                           "tmp-block", "tmp-block-api", "git-guardian", "git-api", "launcher")}
    print("PRISTINE HARNESS PASS " + json.dumps(counts, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
