#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTFILE="${1:-$SCRIPT_DIR/dist/twitch-chat-lurker.js}"
if [[ "$OUTFILE" == *.js ]]; then
    LICENSE_OUT="${OUTFILE%.js}.LICENSE.txt"
else
    LICENSE_OUT="$OUTFILE.LICENSE.txt"
fi

mkdir -p "$(dirname "$OUTFILE")"
cd "$REPO_ROOT"
bun build scripts/twitch-chat-lurker.ts \
    --target=bun \
    --reject-unresolved \
    --banner='// Generated by scripts/build-twitch-chat-lurker.sh; do not edit.' \
    --outfile="$OUTFILE"
cp node_modules/tmi.js/LICENSE "$LICENSE_OUT"
chmod 644 "$LICENSE_OUT"
