# ═══════════════════════════════════════════════════════════════════
# AUTO-GENERATED by Ralph - do not edit manually
# Regenerate with: _ralph_generate_launchers_from_registry
# ═══════════════════════════════════════════════════════════════════

# Bootstrap repoGolem when this file is sourced directly.
if ! typeset -f repoGolem >/dev/null 2>&1 && [[ -f "$HOME/.config/ralphtools/ralph.zsh" ]]; then
  source "$HOME/.config/ralphtools/ralph.zsh"
fi

repoGolem alpha "/fixture/gits/alpha" context7
repoGolem beta "/home/fixture/Gits/beta" 
repoGolem gamma "/fixture/gits/gamma" context7 browser-tools
repoGolem 6pm-svc "/fixture/gits/6pm svc" figma-remote

# Aliases (from funcAlias / launcherAliasPrefix in registry)
alias alfClaude=alphaClaude
function alphaCore() { alphaClaude "$@"; }
function alphaCoreClaude() { alphaClaude "$@"; }
function alphaCoreCodex() { alphaCodex "$@"; }
function alphaCoreGemini() { alphaGemini "$@"; }
function alphaCoreCursor() { alphaCursor "$@"; }
function alphaCoreKiro() { alphaKiro "$@"; }
alias betaClaude=betaClaude
function sixPm() { 6pm-svcClaude "$@"; }
function sixPmClaude() { 6pm-svcClaude "$@"; }
function sixPmCodex() { 6pm-svcCodex "$@"; }
function sixPmKiro() { 6pm-svcKiro "$@"; }
